#services:
#  postgres:
#    image: postgres:latest
#    container_name: banking_new
#    environment:
#      POSTGRES_USER: root
#      POSTGRES_PASSWORD: "123"
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#
#volumes:
#  postgres_data: